server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/(orders|cache|analytics|customers|inventory|health) {
        proxy_pass http://read-api:8002;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
